import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

declare const Bun: {
  build(options: {
    entrypoints: string[];
    target: "bun";
    format: "esm";
    minify: boolean;
    sourcemap: "none";
  }): Promise<{
    success: boolean;
    outputs: Array<{ text(): Promise<string> }>;
    logs: Array<{ message: string }>;
  }>;
};

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const entrypoint = resolve(root, "src", "opencode-plugin-entry.ts");
const generatedPath = resolve(
  root,
  "src",
  "generated",
  "first-party-plugin.ts",
);
const check = process.argv.includes("--check");

const build = await Bun.build({
  entrypoints: [entrypoint],
  target: "bun",
  format: "esm",
  minify: false,
  sourcemap: "none",
});
if (!build.success || build.outputs.length !== 1) {
  const detail = build.logs.map((log) => log.message).join("\n");
  throw new Error(`Unable to build first-party plugin bundle: ${detail}`);
}

const bundle = await build.outputs[0].text();
const generated = [
  "// Generated by scripts/build-first-party-plugin.ts. Do not edit by hand.",
  `export const GENERATED_FIRST_PARTY_PLUGIN_SOURCE = ${JSON.stringify(bundle)};`,
  "",
].join("\n");

function normalizeLineEndings(value: string): string {
  return value.replace(/\r\n/g, "\n");
}

if (check) {
  const current = await readFile(generatedPath, "utf8").catch(() => "");
  if (normalizeLineEndings(current) !== normalizeLineEndings(generated)) {
    throw new Error(
      "First-party plugin bundle is stale; run `bun run build:plugin`",
    );
  }
} else {
  await mkdir(dirname(generatedPath), { recursive: true });
  await writeFile(generatedPath, generated, "utf8");
}
