export const FIRST_PARTY_PLUGIN_PROTOCOL = 10;
export const PLUGIN_PROBE_ENV = "ORGANUM_CODE_PLUGIN_PROBE_FILE";
export const ORGANUM_CODE_ROLE_ENV = "ORGANUM_CODE_ROLE";
export const ORGANUM_CODE_INTENT_ENV = "ORGANUM_CODE_INTENT";
export const ORGANUM_CODE_ORGANUM_BIN_ENV = "ORGANUM_CODE_ORGANUM_BIN";
export const ORGANUM_CODE_PERSONA_ENV = "ORGANUM_CODE_PERSONA";
export const ORGANUM_CODE_WORKSPACE_ENV = "ORGANUM_CODE_WORKSPACE";
export const ORGANUM_CODE_HUB_DIRECTORY_ENV = "ORGANUM_CODE_HUB_DIR";
export const ORGANUM_CODE_STATE_DIRECTORY_ENV = "ORGANUM_CODE_STATE_DIR";
export const ORGANUM_CODE_PROJECT_CONTRACT_ENV =
  "ORGANUM_CODE_PROJECT_CONTRACT";
export const ORGANUM_CODE_OPENCODE_CAST_RECEIPT_ENV =
  "ORGANUM_CODE_OPENCODE_CAST_RECEIPT";
